module.exports = {
	// "467b712f6f3dd1baad34f7b11b75f7d1": {
 //        typeOfMachine: "IpsoWasher_W10kg",
 //        machineName: "SP-W1",
 //        active: false,
 //        sent: false,
 //        locked: false,
 //        amountPaid: 0,
 //        totalPaid: 0,
 //        wechatPaid: 0,
 //        totalWechat: 0,
 //        totalManual: 0,
 //        coinPaid: 0,
 //        manualPaid: 0,
 //        totalCoin: 0,
 //        totalRun: 0,
 //        coldRun: 0,
 //        warmRun: 0,
 //        otherRun: 0,
 //        hotRun: 0,
 //        doneTime: 0,
 //        startTime: 0,
 //        totalTime: 0,
 //        oneRunTime: 25,
 //        lockCounter: 0,
 //        version: 0,
  //   },
    "ff667ad6aeec13ca9b39a69ab1b327d4": {
        typeOfMachine: "IpsoWasher_W10kg",
        machineName: "BBB-W1",
        active: false,
        sent: false,
        locked: false,
        amountPaid: 0,
        totalPaid: 0,
        wechatPaid: 0,
        totalWechat: 0,
        totalManual: 0,
        coinPaid: 0,
        manualPaid: 0,
        totalCoin: 0,
        totalRun: 0,
        coldRun: 0,
        warmRun: 0,
        otherRun: 0,
        hotRun: 0,
        doneTime: 0,
        startTime: 0,
        totalTime: 0,
        oneRunTime: 25,
        lockCounter: 0,
        version: 0,
    },
    "afd3464a6b443af1ec65600881746d73": {
        typeOfMachine: "IpsoWasher_W10kg",
        machineName: "BBB-W2",
        active: false,
        sent: false,
        locked: false,
        amountPaid: 0,
        totalPaid: 0,
        wechatPaid: 0,
        totalWechat: 0,
        totalManual: 0,
        coinPaid: 0,
        manualPaid: 0,
        totalCoin: 0,
        totalRun: 0,
        coldRun: 0,
        warmRun: 0,
        otherRun: 0,
        hotRun: 0,
        doneTime: 0,
        startTime: 0,
        totalTime: 0,
        oneRunTime: 25,
        lockCounter: 0,
        version: 0,
    },
    "b54537db3829bfcaad9ecf7079269477": {
       typeOfMachine: "ipso_dryer_D14kg",
       machineName: "BBB-D1",
       active: false,
       sent: false,
       locked: false,
       amountPaid: 0,
       totalPaid: 0,
       wechatPaid: 0,
       totalWechat: 0,
       totalManual: 0,
       coinPaid: 0,
       manualPaid: 0,
       totalCoin: 0,
       totalRun: 0,
       doneTime: 0,
       startTime: 0,
       totalTime: 0,
       oneRunTime: 5,
       lockCounter: 0,
       version: 0
    },
    "b54537db3829bfcaad9ecf7079269477": {
       typeOfMachine: "ipso_dryer_D14kg",
       machineName: "BBB-D2",
       active: false,
       sent: false,
       locked: false,
       amountPaid: 0,
       totalPaid: 0,
       wechatPaid: 0,
       totalWechat: 0,
       totalManual: 0,
       coinPaid: 0,
       manualPaid: 0,
       totalCoin: 0,
       totalRun: 0,
       doneTime: 0,
       startTime: 0,
       totalTime: 0,
       oneRunTime: 5,
       lockCounter: 0,
       version: 0
    },
    "b0b27916bde5eeef390f6d9c2b6f5419": {
      typeOfMachine: "detergent",
      machineName: "BBB-V1",
      active: false,
      sent: false,
      totalPaid: 0,
      totalWechat: 0,
      totalManual: 0,
      totalCoin: 0,
      detergent: 0,
      beg: 0,
      softnr: 0,
      version: 0,
    }
}
